const sideDishes = [
    { name: "Abacaxi:", price: 2.00 },
    { name: "Amendoim:", price: 2.00 },
    { name: "Aveia:", price: 2.00 },
    { name: "Banana:", price: 2.00 },
    { name: "Bis Preto:", price: 2.50 },
    { name: "Bis Branco:", price: 2.50 },
    { name: "Brigadeiro:", price: 3.00 },
    { name: "Beijinho:", price: 3.00 },
    { name: "Chatili:", price: 2.50 },
    { name: "Chocolate em Gotas:", price: 3.00 },
    { name: "Confete:", price: 2.50 },
    { name: "Calda de Chocolate:", price: 2.50 },
    { name: "Calda de Morango:", price: 2.50 },
    { name: "Creme de Leitinho:", price: 6.00 },
    { name: "Creme de Ovomaltine:", price: 7.00 },
    { name: "Dadinho:", price: 2.50 },
    { name: "Diamante Negro:", price: 4.00 },
    { name: "Doce de Leite:", price: 2.00 },
    { name: "Granola:", price: 2.50 },
    { name: "Farinha Láctea:", price: 3.00 },
    { name: "Granulado:", price: 2.00 },
    { name: "Iogurte Morango:", price: 2.00 },
    { name: "Kit Kat:", price: 2.50 },
    { name: "Laka:", price: 4.00 },
    { name: "Leite Condensado:", price: 2.00 },
    { name: "Leite Ninho:", price: 2.50 },
    { name: "Leite em Pó:", price: 2.00 },
    { name: "Mel:", price: 3.00 },
    { name: "Morango:", price: 2.50 },
    { name: "Mousse de Maracujá:", price: 3.00 },
    { name: "Mousse de Morango:", price: 3.00 },
    { name: "Mousse de Limão:", price: 3.00 },
    { name: "Nutella:", price: 6.00 },
    { name: "Nescal Ball:", price: 2.00 },
    { name: "Neston:", price: 2.50 },
    { name: "Ovomaltine:", price: 2.50 },
    { name: "Ouro Branco:", price: 2.50 },
    { name: "Paçoca:", price: 2.00 },
    { name: "Prestígio (coco e granulado):", price: 2.50 },
    { name: "Sonho de Valsa:", price: 2.50 },
    { name: "Space Ball:", price: 2.50 },
    { name: "Sucrilhos:", price: 2.00 },
    { name: "Suflair:", price: 4.50 },
    { name: "Raspas de Chocolate Preto:", price: 3.00 },
    { name: "Raspas de Chocolate Branco:", price: 3.00 },
    { name: "Bolacha Oreo:", price: 2.00 },
    { name: "Creme de Amendoim com pedaços:", price: 5.00 },
];

const cupPrices = [
    { size: "300mL", price: 7.0 },
    { size: "400mL", price: 8.0 },
    { size: "500mL", price: 9.0 },
    { size: "700mL", price: 11.5 },
    { size: "1L", price: 18.0 },
];

export { sideDishes, cupPrices };
